name: kanban_board
description: A Kanban board app with offline mode and Firebase integration
version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.4.0
  firebase_auth: ^5.3.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  file_picker: ^8.3.6 # Updated from ^6.0.0
  drag_and_drop_lists: ^0.4.0
  intl: ^0.19.0
  fluttertoast: ^8.2.0
  uuid: ^4.0.0
  riverpod_annotation: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.0.0
  build_runner: ^2.0.0
flutter:
  uses-material-design: true
