// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCggjtaDrsse3Mkk_p6YDaIRZXg5peqqH4',
    appId: '1:26667134739:web:e63234502a39a31245b4e6',
    messagingSenderId: '26667134739',
    projectId: 'test-db8ea',
    authDomain: 'test-db8ea.firebaseapp.com',
    storageBucket: 'test-db8ea.firebasestorage.app',
    measurementId: 'G-GMHE4TZJPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHCqmt6pIspxglMaXBNVej8xe7KZHCoqg',
    appId: '1:26667134739:android:16fcfdd392f1529d45b4e6',
    messagingSenderId: '26667134739',
    projectId: 'test-db8ea',
    storageBucket: 'test-db8ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOTvGcLpsa56GZnwjG4TiSDc_ZQZREjmM',
    appId: '1:26667134739:ios:0ddffe3c832f7d5d45b4e6',
    messagingSenderId: '26667134739',
    projectId: 'test-db8ea',
    storageBucket: 'test-db8ea.firebasestorage.app',
    iosBundleId: 'com.example.aventusFlutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOTvGcLpsa56GZnwjG4TiSDc_ZQZREjmM',
    appId: '1:26667134739:ios:0ddffe3c832f7d5d45b4e6',
    messagingSenderId: '26667134739',
    projectId: 'test-db8ea',
    storageBucket: 'test-db8ea.firebasestorage.app',
    iosBundleId: 'com.example.aventusFlutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCggjtaDrsse3Mkk_p6YDaIRZXg5peqqH4',
    appId: '1:26667134739:web:d4790afd34eab9b245b4e6',
    messagingSenderId: '26667134739',
    projectId: 'test-db8ea',
    authDomain: 'test-db8ea.firebaseapp.com',
    storageBucket: 'test-db8ea.firebasestorage.app',
    measurementId: 'G-7WFP9E1NBL',
  );
}
